#!/bin/sh

### BEGIN INIT INFO
# Provides:          ip-random
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ip-random
# Description: changement de l'adresse ip a chaque demarrage
### END INIT INFO

# Suppression des anciens fichiers openvpn

rm /etc/openvpn/openvpn.conf /etc/openvpn/auth.txt

# Selection aleatoire des fichiers openvpn.conf

cp /usr/share/openvpn/vpn/*/* /etc/openvpn/

exit 0
