#!/bin/sh

### BEGIN INIT INFO
# Provides:          ip-random
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ip-random
# Description:       ip random at boot
### END INIT INFO

# Delete old files openvpn

rm /etc/openvpn/openvpn.conf /etc/openvpn/auth.txt

# Select random vpn of the files openvpn.conf

cp /usr/share/openvpn/vpn/*/* /etc/openvpn/
